apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: blog_api
  DB_HOST: fullstack-postgres
  DB_DRIVER: postgres
  API_SECRET: secret
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: blog_api
  DB_PORT: "5432"