version: '3'

services:
    db:
        container_name: go_db
        build:
            context: ../
            dockerfile: ./.docker/Dockerfile
        env_file:
            - ../.env
        # environment:
        #     - POSTGRES_USER=${DB_USER}
        #     - POSTGRES_PASSWORD=${DB_PASSWORD}
        #     - POSTGRES_DB=${DB_NAME}
        #     - DATABASE_HOST=${DB_HOST}
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data:delegated

volumes:
    db-data: